{{- if .Values.wordpress.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.wordpress.name }}-ingress
  annotations: {{- toYaml .Values.wordpress.ingress.annotations | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.wordpress.ingress.host }}
    http:
      paths:
      - path: {{ .Values.wordpress.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.wordpress.name }}
            port:
              number: 80
{{- end }}

